# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f407c85b0a36596715585025c686df3403fdf2c4e63b1388b4651103abb7240d2568dc5a245541b32215459c0a66ab126514f92e5311f8fedaa26f335a843443

test:
  secret_key_base: 1ecd0716aba40113503f0ddd3567bc9cd018527893243506acb38947116e5ca810831365f52d49ca5a8906615c00863550348637544b2e94ff0e44ef3ab2c23a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
